#!/bin/bash

firstrun() {
        # Initialize data dir if empty
        files_in_data_dir=`ls -1 /data | wc -w`

        # Scheduling a password reset for the root user, both % and localhost are needed.
        if [ $files_in_data_dir = 0 ]; then
                echo "MariaDB initial setup" >> /log/var/mysql.log
                echo "~~~~~~~~~~~~~~~~~~~~~" >> /log/var/mysql.log
                echo "" >> /log/var/mysql.log
                mysql_install_db --user=mysql
                echo -e "GRANT ALL PRIVILEGES ON *.* TO 'xtra'@'%' IDENTIFIED BY '1234' WITH GRANT OPTION;\n" >> /setup.sql
                echo -e "GRANT ALL PRIVILEGES ON *.* TO 'xtra'@'localhost' IDENTIFIED BY '1234' WITH GRANT OPTION;\n" >> /setup.sql
        fi

	cp -r /var/lib/mysql/* /data
	chown -R mysql /data
	chown root /data/debian*
}

main() {

	# Clear start up SQL commands
        echo "" > /setup.sql

	if [[ ! -f /data/debian-10.0.flag ]]
	then
		firstrun
	fi

	echo "datadir=/data" >> /etc/mysql/my.cnf
	echo "wsrep_data_home_dir=/data/" >> /etc/mysql/my.cnf
	#echo "gcache.dir = /var/lib/mysql/" >> /etc/mysql/my.cnf
	#echo "gcache.name = /var/lib/mysql/galera.cache"  >> /etc/mysql/my.cnf

	case "$1" in
		master)
			echo "Starting master"
			echo "wsrep_cluster_address=gcomm://" >> /etc/mysql/my.cnf
			/usr/bin/mysqld_safe --init-file=/setup.sql
			;;
		node)
			echo "Starting node"
			if [[ -z "$2" ]]
			then
				echo "Missing master node IP"
			else
				echo "wsrep_cluster_address=gcomm://$2" >> /etc/mysql/my.cnf
				/usr/bin/mysqld_safe --init-file=/setup.sql
			fi
			;;
		*)
			echo "start <master|node> <master node ip>"
	esac
}

main $@
