[template]
src   = "database_creds"
dest  = "/usr/local/bin/database_creds"
owner = "root"
group = "root"
mode  = "0755"
keys = [
  "/galera/credentials",
]
check_cmd = "/usr/local/bin/check {{ .src }}"
