#!/bin/bash
#
# Grant various credentials to mysql before joining cluster
#

mysql -e 'SET wsrep_on=OFF; GRANT select ON *.* TO "haproxy_check"@"%"'
mysql -e 'SET wsrep_on=OFF; GRANT ALL ON *.* TO "{{ .galera_credentials_repUser }}"@"%" IDENTIFIED BY "{{ .galera_credentials_repPass }}";'
mysql -e 'SET wsrep_on=OFF; GRANT ALL ON *.* TO "{{ .galera_credentials_repUser }}"@"localhost" IDENTIFIED BY "{{ .galera_credentials_repPass }}";'
mysql -e 'SET wsrep_on=OFF; GRANT ALL PRIVILEGES ON *.* TO "{{ .galera_credentials_adminUser }}"@"%" IDENTIFIED BY "{{ .galera_credentials_adminPass }}";'
mysql -e 'SET wsrep_on=OFF; GRANT SUPER ON *.* TO "{{ .galera_credentials_adminUser }}"@"%" WITH GRANT OPTION;'
mysql -e 'FLUSH PRIVILEGES;'

exit 0
